# docker-compose.yml
version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.txt
    volumes:
      - /app/vendor
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true